swagger: '2.0'
info:
  $ref: ./info.yml
schemes:
  - http
basePath: /v1
produces:
  - application/json

paths:
  $ref: ./paths/index.yml

tags:
  - name: promos
    description: Promos management
  - name: auths
    description: Authorizations management
  - name: admins
    description: Admins management
  - name: branches
    description: Branches management

parameters:
  $ref: ./parameters/index.yml

definitions:
  $ref: ./definitions/index.yml
